const PIN = "CAS005";
const EXAM_MIX = { 1: 18, 2: 24, 3: 28, 4: 20 };
const STORE = "sx_cas005_study_v2";
const MASTER_STREAK = 3;
const WEAK_MISSES = 2;

const $ = (id) => document.getElementById(id);
const state = {
  data: null,
  queue: [],
  idx: 0,
  selected: new Set(),
  revealed: false,
  results: [],
  sessionKey: null,
  title: "",
  startSnap: null,
};

const GLOSSARY = {
  ABAC: "Attribute-Based Access Control — grants access from tags on the user and the resource (department, data class), not from a job title alone.",
  AES: "Advanced Encryption Standard — the common symmetric cipher for data at rest and in transit.",
  ALE: "Annualized Loss Expectancy — estimated yearly dollar loss for a risk (SLE × ARO).",
  APT: "Advanced Persistent Threat — a patient, often well-funded attacker who stays inside a network.",
  ARO: "Annualized Rate of Occurrence — how many times a year you expect a given loss event.",
  "ATT&CK": "MITRE ATT&CK — a catalog of real attacker tactics and techniques used to plan detections and tests.",
  AUP: "Acceptable Use Policy — written rules for how staff may use company systems and data.",
  BCP: "Business Continuity Plan — how the business keeps operating through a disruption.",
  BIA: "Business Impact Analysis — which processes matter most and what an outage costs.",
  BYOD: "Bring Your Own Device — personal phones or laptops used for work.",
  CA: "Certificate Authority — issues and vouches for digital certificates.",
  CAPEC: "Common Attack Pattern Enumeration and Classification — a library of how attacks are built.",
  CASB: "Cloud Access Security Broker — a control point between users and cloud apps (visibility, DLP, access).",
  CCPA: "California Consumer Privacy Act — California resident privacy rights (know, delete, opt out of sale).",
  CDN: "Content Delivery Network — copies of content at the edge so pages load faster worldwide.",
  CI: "Continuous Integration — automatically build and test code when it is checked in.",
  "CI/CD": "Continuous Integration / Continuous Delivery — automated build, test, and release pipeline.",
  CIA: "Confidentiality, Integrity, Availability — the three classic security properties.",
  CIS: "Center for Internet Security — publishes prioritized Controls and technical Benchmarks.",
  CISO: "Chief Information Security Officer — the executive who owns the security program.",
  CMDB: "Configuration Management Database — inventory of systems and how they relate.",
  COBIT: "Control Objectives for Information and Related Technologies — an IT governance framework.",
  COPPA: "Children's Online Privacy Protection Act — U.S. rules for collecting data from children under 13.",
  COSO: "Committee of Sponsoring Organizations — internal-control / enterprise-risk framework.",
  CRL: "Certificate Revocation List — a published list of certificates that are no longer trusted.",
  CSP: "Cloud Service Provider — AWS, Azure, GCP, and similar platforms.",
  CVE: "Common Vulnerabilities and Exposures — a public ID for a known software flaw.",
  CVSS: "Common Vulnerability Scoring System — a 0–10 scale for how severe a flaw is.",
  DAST: "Dynamic Application Security Testing — probes a running app the way an attacker would.",
  DLP: "Data Loss Prevention — tools and rules that detect or block sensitive data leaving a channel.",
  DORA: "Digital Operational Resilience Act — EU rules for ICT risk in financial firms.",
  DPO: "Data Protection Officer — the privacy role required under some regimes such as GDPR.",
  DR: "Disaster Recovery — restoring IT after a site or system is lost.",
  EDR: "Endpoint Detection and Response — host telemetry and response on laptops and servers.",
  FQDN: "Fully Qualified Domain Name — a complete hostname such as app.company.com.",
  GDPR: "General Data Protection Regulation — EU personal-data law, including erasure and lawful basis.",
  GRC: "Governance, Risk, and Compliance — how policy, risk decisions, and proof of duty stay aligned.",
  HSM: "Hardware Security Module — tamper-resistant box that stores and uses cryptographic keys.",
  IaaS: "Infrastructure as a Service — you rent VMs, networks, and storage; you still secure the OS and apps.",
  IaC: "Infrastructure as Code — servers and networks defined in files (Terraform, Ansible) instead of click-ops.",
  ICS: "Industrial Control System — computers that run plants, pipelines, and factory floors.",
  IdP: "Identity Provider — the system that authenticates a user and issues a token or assertion.",
  IKE: "Internet Key Exchange — the handshake that sets up an IPsec VPN.",
  IoC: "Indicator of Compromise — a fact (hash, IP, host) that suggests an intrusion.",
  IoT: "Internet of Things — cameras, sensors, and other special-purpose networked devices.",
  IPS: "Intrusion Prevention System — inspects traffic and can block known attack patterns.",
  IR: "Incident Response — detect, contain, eradicate, recover, and learn from an event.",
  ISO: "International Organization for Standardization — among other things, publishes ISO/IEC 27001.",
  ITIL: "IT Infrastructure Library — a service-management framework (change, incident, problem).",
  KMS: "Key Management Service — cloud or on-prem service that creates and controls crypto keys.",
  LDAP: "Lightweight Directory Access Protocol — the common way apps query a directory for users and groups.",
  LGPD: "Lei Geral de Proteção de Dados — Brazil's general data-protection law.",
  MAC: "Media Access Control — the hardware address of a network interface; also Mandatory Access Control in other stems.",
  MDM: "Mobile Device Management — policy and inventory control over phones and tablets.",
  MFA: "Multifactor Authentication — more than one factor (something you know, have, or are).",
  MOU: "Memorandum of Understanding — a written statement of intent between organizations, short of a full contract.",
  NAC: "Network Access Control — decides whether a device may join the network.",
  NDA: "Nondisclosure Agreement — a contract that limits sharing of specified information.",
  NIST: "National Institute of Standards and Technology — publishes CSF, RMF, and many 800-series guides.",
  NX: "No-eXecute (XD) — a CPU flag that stops data pages from running as code.",
  OCSP: "Online Certificate Status Protocol — a live check of whether a certificate is still valid.",
  OIDC: "OpenID Connect — identity layer on OAuth 2.0 so an app can learn who the user is.",
  OSINT: "Open-Source Intelligence — information gathered from public sources.",
  OT: "Operational Technology — controllers and networks that run physical processes.",
  OWASP: "Open Worldwide Application Security Project — web and app security guidance (Top 10, SAMM, ASVS).",
  PaaS: "Platform as a Service — you deploy the app; the provider runs the OS and runtime.",
  PBQ: "Performance-Based Question — a lab-style item, not a single multiple-choice pick.",
  PCI: "Payment Card Industry (DSS) — security standard for environments that handle cardholder data.",
  PHI: "Protected Health Information — health data covered by HIPAA.",
  PII: "Personally Identifiable Information — data that can identify a person.",
  PKI: "Public Key Infrastructure — CAs, certificates, and keys used for identity and encryption.",
  PLC: "Programmable Logic Controller — the rugged computer that runs a machine or process line.",
  RACI: "Responsible, Accountable, Consulted, Informed — a chart of who owns which duty.",
  RBAC: "Role-Based Access Control — access follows a job role, not a one-off permission list.",
  RCE: "Remote Code Execution — an attacker can run their own code on your system from the network.",
  RMF: "Risk Management Framework — NIST process for categorize, select, implement, assess, authorize, monitor.",
  RPO: "Recovery Point Objective — how much data (in time) you can afford to lose.",
  RTO: "Recovery Time Objective — how quickly the process must be back.",
  SaaS: "Software as a Service — the vendor runs the application; you configure and use it.",
  SAML: "Security Assertion Markup Language — XML assertions used to federate login between companies.",
  SAMM: "Software Assurance Maturity Model — a scorecard for how mature your SDLC security is.",
  SAN: "Subject Alternative Name — extra DNS names on one TLS certificate. Also Storage Area Network in other stems.",
  SASE: "Secure Access Service Edge — cloud-delivered network and security stack for users anywhere.",
  SAST: "Static Application Security Testing — scans source or bytecode without running the app.",
  SBOM: "Software Bill of Materials — the ingredient list of libraries inside a product.",
  SCA: "Software Composition Analysis — finds known issues and licenses in third-party packages.",
  SDN: "Software-Defined Networking — the control plane that programs how packets are forwarded.",
  "SD-WAN": "Software-Defined Wide Area Network — policy-based paths across internet and private links.",
  SDLC: "Software Development Life Cycle — the path from design through build, test, release, and maintain.",
  SIEM: "Security Information and Event Management — collects logs and correlates alerts.",
  SLE: "Single Loss Expectancy — dollars lost if the event happens once.",
  SOC: "Security Operations Center — the team that watches alerts and runs detections. Also SOC 2, an attestation report.",
  SOAR: "Security Orchestration, Automation, and Response — playbooks that act on alerts without a human click every time.",
  SQL: "Structured Query Language — the language used to ask a relational database for rows.",
  SSO: "Single Sign-On — one login reused across many apps.",
  STRIDE: "Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege — a design-time threat model.",
  TPRM: "Third-Party Risk Management — how you assess and watch vendors and subprocessors.",
  TTP: "Tactics, Techniques, and Procedures — the playbook an attacker actually uses.",
  TLS: "Transport Layer Security — the protocol that encrypts browser and API connections.",
  USB: "Universal Serial Bus — removable devices that can carry data or malware.",
  VPN: "Virtual Private Network — an encrypted tunnel between two networks or a user and a network.",
  WAF: "Web Application Firewall — filters HTTP(S) attacks against an application.",
  WORM: "Write Once, Read Many — storage that cannot be altered after it is written.",
  XDR: "Extended Detection and Response — correlated detection across email, endpoint, identity, and network.",
  XSS: "Cross-Site Scripting — injecting script into a page other users will run.",
  ZERO: "Zero Trust — never assume the network is friendly; verify user, device, and path continuously.",
};

const THINK = {
  1: "Think like a risk owner: what decision, document, or proof would the board or an auditor accept?",
  2: "Think like an architect: which design choice meets the constraint with the least extra moving parts?",
  3: "Think like an engineer: which control actually changes the system, not just the policy binder?",
  4: "Think like a SOC lead: what evidence or action stops the bleeding first?",
};

const GLOSSARY_VARIANTS = {
  SBOM: ["SBoM"],
  IoC: ["IOC"],
  IdP: ["IDP"],
  IaC: ["IAC"],
  "SD-WAN": ["SDWAN"],
  "CI/CD": ["CI/CD"],
};
